backend:
  name: git-gateway
  branch: master

site_url: https://twoperfect.events
# logo_url: https://your-site.com/images/logo.svg

media_library:
  name: cloudinary
  config:
    cloud_name: two-perfect-events
    api_key: 682651293441357
    # default_transformations:
    #   - - fetch_format: auto
    #       width: 160
    #       quality: auto
    #       crop: scale

media_folder: static/img/events
public_folder: /img/events

collections:
  - name: 'editorials'
    label: 'Editorials'
    folder: 'content/events/editorials'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Alt', name: 'alt', widget: 'text' }
