backend:
  name: git-gateway
  branch: develop

site_url: https://twoperfect.events
# logo_url: https://your-site.com/images/logo.svg

media_library:
  name: cloudinary
  config:
    cloud_name: two-perfect-events
    api_key: 682651293441357
    max_files: 200
    multiple: true
    default_transformations:
      - fetch_format: auto
        quality: auto
        # width: 160
        # crop: scale

media_folder: static/img/events
public_folder: /img/events

collections:
  - name: 'corporate-events'
    label: 'Corporate Events'
    folder: 'content/events/corporate-events'
    slug: '{{title}}'
    preview_path: portfolio/{{slug}}
    create: true
    format: json
    fields:
      - { label: 'slug', name: 'title', widget: 'string' }
      - { label: 'Images', name: 'images', widget: 'image' }
  - name: 'editorials'
    label: 'Editorials'
    folder: 'content/events/editorials'
    slug: '{{title}}'
    preview_path: portfolio/{{slug}}
    create: true
    format: json
    fields:
      - { label: 'slug', name: 'title', widget: 'string' }
      - { label: 'Images', name: 'images', widget: 'image' }
  - name: 'private-events'
    label: 'Private Events'
    folder: 'content/events/private-events'
    slug: '{{title}}'
    preview_path: portfolio/{{slug}}
    create: true
    format: json
    fields:
      - { label: 'slug', name: 'title', widget: 'string' }
      - { label: 'Images', name: 'images', widget: 'image' }
  - name: 'weddings'
    label: 'Weddings'
    folder: 'content/events/weddings'
    slug: '{{title}}'
    preview_path: portfolio/{{slug}}
    create: true
    format: json
    fields:
      - { label: 'slug', name: 'title', widget: 'string' }
      - { label: 'Images', name: 'images', widget: 'image' }
